name:   'BabelFrog'
url:    'http://babelfrog.com'
author: 'Alex Dergachev'

include:  ['_pages']
exclude: ['assets']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

safe:     true
pygments: false
markdown: 'kramdown'
timezone: 'America/Chicago'
