# Site settings
name: BabelFrog
title: Your awesome title
email: alex@evolvingweb.ca
description: "BabelFrog is a Google Chrome extension to help you learn a language as you browse the web."
baseurl: ""
url: "http://babelfrog.com"
source: source
destination: deploy

# Build settings
markdown: kramdown
permalinks: pretty
